### ISSUE TITLE
Acceptable health check mechanism in ngx_stream_upstream_module.

### ISSUE THREAD

**Issue by Maokaman1** [freenginx/nginx#2]
Do you have any plans to discard the "ngx_stream_upstream_module : upstream : server : max_fails+fail_timeout" parameters and implement an acceptable upstream health check mechanism?

**Comment by mdounin** [comment]
Certainly there are no plans to drop the max_fails/fail_timeout mechanism, it is quite reliable health checking mechanism, which is known to work very good in loaded setups, providing very fast issue detection. If it doesn't work for you for some reason, you can always disable it with [max_fails=0](https://freenginx.org/en/docs/http/ngx_http_upstream_module.html#max_fails).

As for other health checking mechanisms, I personally don't have any plans to work on these, at least in the near future. Still, [contributions are welcome](https://freenginx.org/en/docs/contributing_changes.html).

**Comment by mdounin** [comment]
Hope this answers the question.
