### ISSUE TITLE
 Future relationship between freenginx and F5-nginx?

### ISSUE THREAD

**Issue by nisbet-hubbard** [freenginx/nginx#7]
@mdounin, I wish to thank you for your excellent work on nginx over all these years and for providing in your forum answers what’s often the de-facto documentation on tuning issues not explained in the docs. And now you’ve put all of us in your debt again by undertaking to maintain this community fork on your own time!

One thing I would like to learn more about (and which it may be helpful to mention on the project’s home page or FAQ) is the future relationship of the fork to F5-nginx.

Given that you started the project to fight corporate interference rather than out of any disagreements with F5 engineers, I imagine moving forward you would be open to porting patches from F5 if they concern a bug that equally affects freenginx or a feature they develop that you also find useful?

**Comment by mdounin** [comment]
Sure, I'm perfectly open for porting patches (and I usually do it myself for critical fixes, if any). Note though that such patches needs to be reviewed before they can be committed into freenginx, and this might mean they need to be rewritten before accepted.
